version: "3"

services:
  jekyll:
      image: jekyll/jekyll:latest
      command: jekyll serve --watch --force_polling --verbose, bundle
      ports:
        - 4000:4000
      volumes:
        - .:/srv/jekyll
